[project]
name = ""
version = "0.1.0"
description = "연습장"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.3.4",
    "rich>=14.2.0",
    "torch>=2.9.0",
    "tqdm>=4.67.1",
]
